name: flutter_ume_kit_console
description: Show debugPrint kit for flutter_ume.
version: 1.1.0
homepage: https://github.com/bytedance/flutter_ume
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  share_plus: ^7.2.1
  shared_preferences: ^2.0.6
  flutter_ume:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/flutter_ume
      ref: flutter_3.27.1_20241217 # flutter_ume_1.1.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
