name: shared_preferences_linux
description: Linux implementation of the shared_preferences plugin
repository: https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences_linux
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.4.1

environment:
  # sdk: ^3.6.0
  # flutter: ">=3.27.0"
  sdk: ^3.3.4
  flutter: ">=3.19.6"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      linux:
        dartPluginClass: SharedPreferencesLinux

dependencies:
  file: ">=6.0.0 <8.0.0"
  flutter:
    sdk: flutter
  path: ^1.8.0
  path_provider_linux: ^2.0.0
  path_provider_platform_interface: ^2.0.0
  # shared_preferences_platform_interface: ^2.4.0
  shared_preferences_platform_interface:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_platform_interface
      ref: flutter_3.19.6_20240726_rc01

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - persistence
  - shared-preferences
  - storage
