name: shared_preferences
description: Flutter plugin for reading and writing simple key-value pairs.
  Wraps NSUserDefaults on iOS and SharedPreferences on Android.
repository: https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.5.3+20240726

environment:
  # sdk: ^3.6.0
  # flutter: ">=3.27.0"
  sdk: ^3.3.4
  flutter: ">=3.19.6"

flutter:
  plugin:
    platforms:
      android:
        default_package: shared_preferences_android
      ios:
        default_package: shared_preferences_foundation
      linux:
        default_package: shared_preferences_linux
      macos:
        default_package: shared_preferences_foundation
      web:
        default_package: shared_preferences_web
      windows:
        default_package: shared_preferences_windows

dependencies:
  flutter:
    sdk: flutter
  # shared_preferences_android: ^2.3.4
  # shared_preferences_foundation: ^2.5.0
  # shared_preferences_linux: ^2.4.0
  # shared_preferences_platform_interface: ^2.4.0
  # shared_preferences_web: ^2.4.0
  # shared_preferences_windows: ^2.4.0
  shared_preferences_platform_interface:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_platform_interface
      ref: flutter_3.19.6_20250807_rc02
  shared_preferences_android:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_android
      ref: flutter_3.19.6_20250807_rc02
  shared_preferences_foundation:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_foundation
      ref: flutter_3.19.6_20250807_rc02
  shared_preferences_linux:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_linux
      ref: flutter_3.19.6_20250807_rc02
  shared_preferences_web:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_web
      ref: flutter_3.19.6_20250807_rc02
  shared_preferences_windows:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_windows
      ref: flutter_3.19.6_20250807_rc02

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.9.0

topics:
  - persistence
  - shared-preferences
  - storage
