name: example
description: A new Flutter project.
version: 1.0.1
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.3
  # For Dio Kit
  dio: ^5.4.0
  flutter_ume: 1.1.2
  flutter_ume_kit_ui: 1.1.1
  flutter_ume_kit_perf: 1.0.0
  flutter_ume_kit_show_code: 1.0.0
  flutter_ume_kit_device: 1.0.0
  flutter_ume_kit_console: 1.1.0
  flutter_ume_kit_dio: 1.0.0

dependency_overrides:
  vm_service: ^13.0.0
  flutter_ume:
    path: ../

dev_dependencies:
  flutter_driver:
    sdk: flutter
  test: ^1.16.6
  flutter_ume:
    path: ../
  flutter_ume_kit_ui:
    path: ../kits/flutter_ume_kit_ui
  flutter_ume_kit_perf:
    path: ../kits/flutter_ume_kit_perf
  flutter_ume_kit_show_code:
    path: ../kits/flutter_ume_kit_show_code
  flutter_ume_kit_device:
    path: ../kits/flutter_ume_kit_device
  flutter_ume_kit_console:
    path: ../kits/flutter_ume_kit_console
  flutter_ume_kit_dio:
    path: ../kits/flutter_ume_kit_dio
  flutter_ume_kit_channel_monitor:
    path: ../kits/flutter_ume_kit_channel_monitor
  
flutter:
  uses-material-design: true
