name: shared_preferences_web_integration_tests
publish_to: none

environment:
  # sdk: ^3.6.0
  # flutter: ">=3.27.0"
  sdk: ^3.3.4
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  # shared_preferences_platform_interface: ^2.4.0
  shared_preferences_platform_interface:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_platform_interface
      ref: flutter_3.19.6_20250807_rc01
  shared_preferences_web:
    path: ../
  # web: ^1.0.0
  web: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
