name: shared_preferences_foundation
description: iOS and macOS implementation of the shared_preferences plugin.
repository: https://github.com/flutter/packages/tree/main/packages/shared_preferences/shared_preferences_foundation
issue_tracker: https://github.com/flutter/flutter/issues?q=is%3Aissue+is%3Aopen+label%3A%22p%3A+shared_preferences%22
version: 2.5.4

environment:
  # sdk: ^3.6.0
  # flutter: ">=3.27.0"
  sdk: ^3.3.4
  flutter: ">=3.19.6"

flutter:
  plugin:
    implements: shared_preferences
    platforms:
      ios:
        pluginClass: SharedPreferencesPlugin
        dartPluginClass: SharedPreferencesFoundation
        sharedDarwinSource: true
      macos:
        pluginClass: SharedPreferencesPlugin
        dartPluginClass: SharedPreferencesFoundation
        sharedDarwinSource: true

dependencies:
  flutter:
    sdk: flutter
  # shared_preferences_platform_interface: ^2.4.0
  shared_preferences_platform_interface:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/shared_preferences/shared_preferences_platform_interface
      ref: flutter_3.19.6_20240726_rc01

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^22.4.1

topics:
  - persistence
  - shared-preferences
  - storage
