name: webview_jsbridge_x
description: A flutter jsbridge package compatible with webview_flutter, no native dependence.
version: 1.0.5
homepage: https://github.com/KouYiGuo/webview_jsbridge_x

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.1"

dependencies:
  flutter:
    sdk: flutter

  webview_flutter: ^4.4.2

dev_dependencies:
  # flutter_test:
  #   sdk: flutter

flutter:
  assets:
    - assets/
