name: wakelock_macos
description: >-2
  macOS platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.4.0
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_macos

environment:
  sdk: '>=2.12.0'
  flutter: '>=1.24.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  wakelock_platform_interface:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/wakelock/wakelock_platform_interface
      ref: flutter_3.16.3_20240318 # wakelock_0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WakelockMacosPlugin
        fileName: wakelock_macos.dart
