name: flutter_ume_kit_channel_monitor
description: channel monitor kit for flutter_ume
version: 0.0.1
homepage: https://github.com/bytedance/flutter_ume
publish_to: none

environment:
  sdk: ^3.3.4
  flutter: ^3.19.6

dependencies:
  flutter:
    sdk: flutter
  flutter_ume:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/flutter_ume
      ref: flutter_3.19.6_20250807_rc02 # flutter_ume_1.1.2
  rxdart: ^0.28.0

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  flutter_lints: ^3.0.1
