name: flutter_ume_kit_perf
description: Performance kits for flutter_ume.
version: 1.0.0
homepage: https://github.com/bytedance/flutter_ume
publish_to: none

environment:
  sdk: ^3.6.0
  flutter: ^3.27.1

dependencies:
  flutter:
    sdk: flutter
  vm_service: ^15.0.0
  flutter_ume:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/flutter_ume
      ref: flutter_3.27.1_20241217 # flutter_ume_1.1.2
dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  mockito: ^5.0.12
  flutter_coverage_badge:
    git:
      url: https://github.com/smileShirely/flutter_coverage_badge.git
      ref: 59b7580f406bb712e9d9049c8c99212946e34f65
