name: wakelock_windows
description: >-2
  Windows platform implementation of the wakelock_platform_interface for the wakelock plugin.
version: 0.2.1
repository: https://github.com/creativecreatorormaybenot/wakelock/tree/main/wakelock_windows

environment:
  sdk: '>=2.12.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  wakelock_platform_interface:
    git:
      url: https://github.com/netvue/flutter_external_packages
      path: packages/wakelock/wakelock_platform_interface
      ref: flutter_3.24.0_20241203 # wakelock_0.6.2
  win32: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

# todo: use dartPluginClass declaration once that lands on stable (https://github.com/flutter/flutter/issues/52267_
#flutter:
#  plugin:
#    platforms:
#      windows:
#        dartPluginClass: WakelockWindows
