name: shared_preferences_tool
description: "DevTools extension for package:shared_preferences. Manage SharedPreferences efficiently. Edit, search, and view keys."
publish_to: 'none'

version: 1.0.1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  devtools_app_shared: '>=0.0.9 <0.1.0'
  devtools_extensions: '>=0.0.9 <0.1.0'
  flutter:
    sdk: flutter
  # vm_service: '>=14.3.0 <16.0.0'
  vm_service: '>=11.0.0 <16.0.0'

dev_dependencies:
  # build_runner: ^2.4.10
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  mockito: 5.4.4

flutter:
  uses-material-design: true
